-- Tabla para gestionar las relaciones entre tablas y usuarios colaboradores
-- Los colaboradores serán notificados de cualquier cambio en los registros de la tabla
CREATE TABLE "table_collaborators" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "table_id" INT NOT NULL,
    "user_id" INT NOT NULL,
    "assigned_by" INT NOT NULL, -- usuario que asignó al colaborador
    "assigned_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "is_active" BOOLEAN DEFAULT TRUE,
    "notes" TEXT, -- notas opcionales sobre la asignación
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    -- Claves foráneas
    CONSTRAINT fk_table_collaborators_table FOREIGN KEY ("table_id") REFERENCES "tables" ("id") ON DELETE CASCADE,
    CONSTRAINT fk_table_collaborators_user FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE,
    CONSTRAINT fk_table_collaborators_assigned_by FOREIGN KEY ("assigned_by") REFERENCES "users" ("id") ON DELETE CASCADE,
    
    -- Constraint único para evitar duplicados
    CONSTRAINT uk_table_collaborators_table_user UNIQUE ("table_id", "user_id")
);

-- Índices para optimizar consultas
CREATE INDEX idx_table_collaborators_table_id ON "table_collaborators" ("table_id");
CREATE INDEX idx_table_collaborators_user_id ON "table_collaborators" ("user_id");
CREATE INDEX idx_table_collaborators_active ON "table_collaborators" ("is_active");

-- Comentarios para documentar la tabla
COMMENT ON TABLE "table_collaborators" IS 'Tabla para gestionar colaboradores que reciben notificaciones de cambios en tablas lógicas del sistema';
